---
# This configuration should only have static settings.

# Encoding Config
ffmpeg_compiled: "ffmpeg"
ffprobe_compiled: "ffprobe"
target_aspect_ratio: 1.7777778
multi_upload_barrier: 2000000000

# Heal settings
heal_start: 1
heal_end: 144

# https://github.com/armbox/edux/issues/70
global_timeout: 300

# ----------
##---
# This is a list of encodes and their respective course
# boolean matches
encode_dict:
    review_proc:
        - review
    mobile_override:
        - override
    s3_proc:
        - mobile_low
        - audio_mp3
        - desktop_mp4
        - hls
    yt_proc:
        - youtube

##---
# This is a list of encode profiles and their val profile matches
# boolean matches
val_profile_dict:
    mobile_low:
        - mobile_low
    desktop_mp4:
        - desktop_mp4
    override:
        - desktop_mp4
        - mobile_low
    mobile_high:
        - mobile_high
    audio_mp3:
        - audio_mp3
    youtube:
        - youtube
    review:
    hls:
        - hls
